api_login_check:
    path: /api/login_check
api_change_password:
    path: /api/change_password
    controller: App\Controller\UserController:changePassword
    methods: POST
api_get_user:
    path: /api/user
    controller: App\Controller\UserController::getCurrentUser
    methods: GET
api_logout:
    path: /api/logout
    controller: App\Controller\UserController::logout
    methods: POST
api_ping:
    path: /api/public/ping
    controller: App\Controller\UserController::ping
    methods: GET
api_get_texts:
    path: /api/public/texts
    controller: App\Controller\TextController::getAllTexts
    methods: GET
api_create_text:
    path: /api/texts
    controller: App\Controller\TextController::createText
    methods: POST
