version: "3"

services:
  database:
    container_name: db-portfolio
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: portfolio
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "6033:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backend
  php:
    container_name: php-portfolio
    build:
      context: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/symfony_docker
    depends_on:
      - database
    networks:
      - backend
  nginx:
    container_name: nginx-portfolio
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/symfony_docker
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - backend

networks:
  backend:
